# Generated by Django 3.1.14 on 2022-06-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ethereum_events', '0005_auto_20180713_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daemon',
            name='id',
        ),
        migrations.AddField(
            model_name='daemon',
            name='blockchain_id',
            field=models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='daemon',
            name='blockchain_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='daemon',
            name='ethereum_geth_poa',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daemon',
            name='ethereum_logs_batch_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daemon',
            name='ethereum_logs_filter_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daemon',
            name='ethereum_logs_filter_getlogs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daemon',
            name='ethereum_node_timeout',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daemon',
            name='ethereum_node_uri',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='monitoredevent',
            name='daemon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_ethereum_events.daemon'),
        ),
    ]
