# Generated by Django 3.1.14 on 2022-06-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ethereum_events', '0006_remove_daemon_id_daemon_blockchain_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monitoredevent',
            unique_together={('daemon_id', 'topic', 'contract_address')},
        ),
    ]
